#!/bin/bash
# Full-stack integration test script for ADK Platform
# Usage: ./scripts/test/test-integration.sh [--backend-only] [--frontend-only] [--verbose]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BACKEND_PORT=8080
FRONTEND_PORT=4000
POSTGRES_PORT=5433

# Parse arguments
BACKEND_ONLY=false
FRONTEND_ONLY=false
VERBOSE=false

for arg in "$@"; do
    case $arg in
        --backend-only)
            BACKEND_ONLY=true
            shift
            ;;
        --frontend-only)
            FRONTEND_ONLY=true
            shift
            ;;
        --verbose|-v)
            VERBOSE=true
            shift
            ;;
        *)
            ;;
    esac
done

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed"
        exit 1
    fi

    # Check Poetry
    if ! command -v poetry &> /dev/null; then
        log_error "Poetry is not installed"
        exit 1
    fi

    # Check Node.js
    if ! command -v node &> /dev/null; then
        log_error "Node.js is not installed"
        exit 1
    fi

    log_success "All prerequisites met"
}

# Check if PostgreSQL is running
check_postgres() {
    log_info "Checking PostgreSQL connection..."

    if docker-compose -f "$PROJECT_ROOT/docker-compose.yml" ps postgres | grep -q "Up"; then
        log_success "PostgreSQL is running"
        return 0
    else
        log_warning "PostgreSQL is not running. Starting it..."
        docker-compose -f "$PROJECT_ROOT/docker-compose.yml" up -d postgres
        sleep 5  # Wait for PostgreSQL to be ready

        # Wait for PostgreSQL to be ready (up to 30 seconds)
        for i in {1..30}; do
            if docker-compose -f "$PROJECT_ROOT/docker-compose.yml" exec -T postgres pg_isready -U adk_user -d adk_platform &> /dev/null; then
                log_success "PostgreSQL is ready"
                return 0
            fi
            sleep 1
        done

        log_error "PostgreSQL failed to start"
        return 1
    fi
}

# Run database migrations
run_migrations() {
    log_info "Running database migrations..."
    cd "$PROJECT_ROOT"
    poetry run alembic upgrade head
    log_success "Migrations complete"
}

# Run backend integration tests
run_backend_tests() {
    log_info "Running backend integration tests..."
    cd "$PROJECT_ROOT"

    PYTEST_ARGS="-v --cov=src --cov-report=term-missing"

    if [ "$VERBOSE" = true ]; then
        PYTEST_ARGS="$PYTEST_ARGS -s"
    fi

    poetry run pytest tests/integration/ $PYTEST_ARGS

    log_success "Backend integration tests passed"
}

# Run frontend tests
run_frontend_tests() {
    log_info "Running frontend tests..."
    cd "$PROJECT_ROOT/frontend"

    # Run unit tests
    npm run test

    log_success "Frontend tests passed"
}

# Run E2E tests
run_e2e_tests() {
    log_info "Running E2E tests..."
    cd "$PROJECT_ROOT/frontend"

    # Install Playwright browsers if needed
    npx playwright install chromium --with-deps 2>/dev/null || true

    # Run E2E tests
    npm run test:e2e

    log_success "E2E tests passed"
}

# Health check for backend
backend_health_check() {
    log_info "Performing backend health check..."

    if curl -s "http://localhost:$BACKEND_PORT/health/" | grep -q "healthy"; then
        log_success "Backend is healthy"
        return 0
    else
        log_error "Backend health check failed"
        return 1
    fi
}

# Generate test report
generate_report() {
    log_info "Generating test report..."

    REPORT_DIR="$PROJECT_ROOT/test-reports"
    mkdir -p "$REPORT_DIR"

    # Backend coverage report is generated by pytest

    # Frontend coverage report
    if [ -d "$PROJECT_ROOT/frontend/coverage" ]; then
        cp -r "$PROJECT_ROOT/frontend/coverage" "$REPORT_DIR/frontend-coverage"
    fi

    # E2E test report
    if [ -d "$PROJECT_ROOT/frontend/playwright-report" ]; then
        cp -r "$PROJECT_ROOT/frontend/playwright-report" "$REPORT_DIR/e2e-report"
    fi

    log_success "Test reports generated in $REPORT_DIR"
}

# Main execution
main() {
    echo ""
    echo "========================================"
    echo "  ADK Platform Integration Tests"
    echo "========================================"
    echo ""

    check_prerequisites

    if ! check_postgres; then
        exit 1
    fi

    run_migrations

    if [ "$FRONTEND_ONLY" = false ]; then
        run_backend_tests
    fi

    if [ "$BACKEND_ONLY" = false ]; then
        run_frontend_tests
    fi

    generate_report

    echo ""
    echo "========================================"
    log_success "All integration tests passed!"
    echo "========================================"
}

main
